### ISSUE TITLE
Port to python2

### ISSUE THREAD

**Issue by arpit1997** [ITCoders/Human-detection-and-Tracking#10]
**Port this repository to python2 from python3**
- code should support python2.7  and opencv3.x
- other useful scripts in `scripts folder` should also be converted to python2
- make a separate branch for python2
- multiple pull requests are allowed for this.

:smiley:

**Comment by rsh7** [comment]
Hello, 
I was porting the code to python2
But, before it while running the present code which is in python3 it is showing errors.
According to the issue, should not the code error free?

**Comment by arpit1997** [comment]
Thank you for trying.
I saw one code that was already in python2, other than that i don't see any mistakes in the codes. Mention the logs and error messages for the codes that have mistakes, feel free to send a PR if you can fix this issue, partially fixed issue will also be fine.
I will try to go through the codes once again.
:m:  :smiley_cat:

**Comment by rsh7** [comment]
**Alright! I'll check.
Thanks!**
