### ISSUE TITLE
Port to C++

### ISSUE THREAD

**Issue by arpit1997** [ITCoders/Human-detection-and-Tracking#11]
**Port this repo to C++**
- code should be written in C++.
- make a separate branch for this.
- functionality should be same and performance should be better.
- useful scripts in scripts folder should also be ported.
- multiple pull requests are allowed for this but make sure that you are on correct path
  :smile: :smile:

**Comment by arpit1997** [comment]
@prsntmaurya Can you do this ?

**Comment by prsntmaurya** [comment]
Yes, need some time.

**Comment by ArshadAliDev** [comment]
i am trying to execute a program similar to this(Face Recognition using LBPH). 
in cmd i have typed
 `python <pythonFileName> <'C:\FaceRocogProject\Face recog sqllite\test.mp4'>`
i see no output nor error. What is the solution for this ?

**Comment by arpit1997** [comment]
>i am trying to execute a program similar to this(Face Recognition using LBPH).
in cmd i have typed
python <pythonFileName> <'C:\FaceRocogProject\Face recog sqllite\test.mp4'>
i see no output nor error. What is the solution for this ?

Open a seperate issue for this @codeArshad and mention the required details like what is the exact command that you ran and may be a screenshot of the output in the conosole. 

This issue for porting the code to C++ so it will be lot easier if you open a new issue regarding this problem.
😸 🛩

**Comment by arpit1997** [comment]
@prsntmaurya  I have merged the C++ branch to master branch please check it it is working fine or not. Ping me for any issue. https://github.com/ITCoders/Human-detection-and-Tracking/commit/d12c4c2f8eae9649eb7fc0f8c927f7d00b528da6

**Comment by prsntmaurya** [comment]
@arpit1997 I have checked it, it's working fine.
