### ISSUE TITLE
video for test

### ISSUE THREAD

**Issue by ouarrtaha** [ITCoders/Human-detection-and-Tracking#17]
hello 
can you send me a video to test the project, 
i used a video found on the net but i got just this result
------------------------
E:\peopleTracking\pytracking\Human-detection-and-Tracking-master\Human-detection-and-Tracking-master\videos\v1.mp4*.mp4
[]
------------------------

**Comment by arpit1997** [comment]
What is the python version you are using?
If it is python3.4 then its fine and i will check for this issue.
If you are using python2.7 then this script won't work
>opencv
Installation in linux: For complete installation of opencv in ubuntu you can refer here.
Installation in windows For complete installation of opencv in windows you can refer here
python3
In Ubuntu python 3.4 can be installed via terminal with the command given below: sudo apt-get install python3
python libraries: Here is a list of all the python dependencies
Python Image Library (PIL)
Imutils
numpy

These are the requirements for the script to run correctly. 😄

**Comment by ouarrtaha** [comment]
i use python 3.6.0

**Comment by arpit1997** [comment]
Try python3.4
Post the command also that you have used

**Comment by ouarrtaha** [comment]
ok it's fine , i changed the line 115 in main.py to
list_of_videos = glob.glob(os.path.join(os.path.abspath(path), f))

**Comment by arpit1997** [comment]
Closing this now @hardjob  :)
