### ISSUE TITLE
Confidence values in both C++ and python version of the code are significantly different

### ISSUE THREAD

**Issue by prsntmaurya** [ITCoders/Human-detection-and-Tracking#21]
Both are using same "model.yaml" file and LBPHFaceRecognizer algorithm.

**Comment by arpit1997** [comment]
@prsntmaurya  Can you provide the example for both of confidence values?

**Comment by prsntmaurya** [comment]
Yes, confidence values for video 5.mp4 is as follows:
a) for C++ version it lies roughly in range 60-70.
b) for Python version it is in the range 100-190.
