### ISSUE TITLE
How to detect faces and divide them to save ?

### ISSUE THREAD

**Issue by wukuai** [ITCoders/Human-detection-and-Tracking#22]

**Comment by arpit1997** [comment]
#22 
> How to detect faces and divide them to save 

I am not clear what you are asking. I understand two things from this issue:
1. You want to train a model for face recognition
2. you already have a model and want to know how to use that model to make predictions and interpret the results.

Please clear out your question so it is for us to provide the appropriate solution. :smile_cat:

**Comment by wukuai** [comment]
I want to train a model for face recognition. 
Now I have so many photos of my face and I want to detect faces in these photos and divide them to save in './data'.
In the './scripts' I can't find which script to do the work mentioned above. :grin:

**Comment by arpit1997** [comment]
I will walk you through the steps:
- [This](https://github.com/ITCoders/Human-detection-and-Tracking/blob/master/create_face_model.py) is the file that we have used to train our face recognition model

- We have a [specific filename format](https://github.com/ITCoders/Human-detection-and-Tracking/tree/master/data) that we use for images. The format `subjectX.Y.jpg` where X is the subject label and Y is an auto increment number just for different images. 

 - next you need to run the file mentioned above `create_face_model.py` 
` ` `
python3 create_face_model.py /path/to/images/directory
` ` `
Let me know if you find any problem in that.

**Comment by arpit1997** [comment]
closing this issue #22 with answer:
>I will walk you through the steps:
- [This](https://github.com/ITCoders/Human-detection-and-Tracking/blob/master/create_face_model.py) is the file that we have used to train our face recognition model
- We have a [specific filename format](https://github.com/ITCoders/Human-detection-and-Tracking/tree/master/data) that we use for images. The format `subjectX.Y.jpg` where X is the subject label and Y is an auto increment number just for different images. 
 - next you need to run the file mentioned above `create_face_model.py` 
` ` `
python3 create_face_model.py /path/to/images/directory
` ` `
Let me know if you find any problem in that.
