### ISSUE TITLE
Can I able to find coordinate values of bounding boxes.

### ISSUE THREAD

**Issue by shabbeersh** [ITCoders/Human-detection-and-Tracking#26]
# Issues should contain the following details which increases the probability of it get resolved quickly

* **Exact error or Issue details**
* **OpenCV Version**
* **Python Version**
* **Operating System**
* **Changes done, if any in the original code**

**Comment by prsntmaurya** [comment]
yes sure,

If you are using **Python** version of the code then you can get the coordinates of the rectangles as follows:
for people detection, it stored in the variable ' _rects_ '  in function named 'def _detect_people_'
for face coordinates, you can refer to '_face_' variable in '_draw_faces_' function.

**Comment by prsntmaurya** [comment]
I hope your problem is resolved for now.
