### ISSUE TITLE
This node is not a map nor an empty collection

### ISSUE THREAD

**Issue by RobertFlorinDragut** [ITCoders/Human-detection-and-Tracking#28]
Hello,

I have tried to follow your instructions from Issue#25, but could not manage to make it work. When I am trying to run the command py create_face_model.py -i data/ I am getting the following error:
ImportError: No module named cv2

Also, if I erase the first line on create_face_model.py, #!/usr/bin/python, I am getting this error:
C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:636: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If yo
u are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

Thank you in advance.
I am using python 3.6

**Comment by RobertFlorinDragut** [comment]
Update
I am getting these errors:
File "C:/Users/Robert/Desktop/Human-detection-and-Tracking-master/create_face_model.py", line 55, in <module>
    images, labels = get_images_and_labels(path)
  File "C:/Users/Robert/Desktop/Human-detection-and-Tracking-master/create_face_model.py", line 44, in get_images_and_labels
    image[y: y + h, x: x + w])
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:636: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon supp

**Comment by prsntmaurya** [comment]
Hi Robert,
Are you able to run any sample code in OpenCV, because it seems like you haven't installed OpenCV properly.

**Comment by RobertFlorinDragut** [comment]
Hi,

I haven`t tried to run other programs that use opencv, since this was the first time I actually used Python. On my project it says that opencv and opencv-contrib are installed. I truly do not know what the issues is since I have tried to use the program on another pc and there it works. Also, I am getting a new error, that cv2 has no attribute called face.

Thank you.

**Comment by prsntmaurya** [comment]
Hi Robert,
The error "cv2 has no module named face" occurs when OpenCV is not build with contrib modules.

**Comment by prsntmaurya** [comment]
I haven't received any replies, I hope this issue is resolved.
