### ISSUE TITLE
this code with python3.6 and opencv3.4

### ISSUE THREAD

**Issue by fatemetardasti96** [ITCoders/Human-detection-and-Tracking#29]
I have a problem and I can not run my code. I have python 3.6 with opencv 3.4. It seems coding is not compatible with this version so I changed it a little. 
At first I had problem with line 16:   recognizer = cv2.face.createLBPHFaceRecognizer()
so I changed it into recognizer = cv2.face.LBPHFaceRecognizer_create()

then I had problem with line 137: recognizer.load("model.yaml")
And I changed it again to: recognizer.read("model.yaml")

But now I found the error saying : error: (-2) The node is neither a map nor 
an empty collection in function cvGetFileNodeByName

And I have no idea what to do with this.

**Comment by prsntmaurya** [comment]
Hi,
This issue is already addressed in issue #25.
Please refer to it.

Reopen the issue if it is not resolved.
