### ISSUE TITLE
The node is neither a map nor an empty collection in function 'cvGetFileNodeByName'

### ISSUE THREAD

**Issue by MounirB** [ITCoders/Human-detection-and-Tracking#30]
Hello everybody, 

When I run main.py, I get the following error :
```
Traceback (most recent call last):
  File "/home/mounir/PycharmProjects/Human-detection-and-Tracking-master/main.py", line 137, in <module>
    recognizer.read("model.yaml")
cv2.error: OpenCV(4.0.0-pre) /home/mounir/opencv/modules/core/src/persistence_c.cpp:757: error: (-2:Unspecified error) The node is neither a map nor an empty collection in function 'cvGetFileNodeByName'
```
I have the latest OpenCV version installed

## Details
* **Exact error or Issue details**
* **OpenCV Version ** : 4.0.0-pre (I know you told us to opt for 3.1.1
* **Python Version** : 3.6
* **Operating System** : Ubuntu 18.04
* **Changes done, if any in the original code** : Yes, some changes have been done.

`recognizer = cv2.face.LBPHFaceRecognizer_create()`
instead of 
`recognizer = cv2.face.createLBPHFaceRecognizer()`

and 

`recognizer.read("model.yaml")`
instead of
`recognizer.load("model.yaml")`

Thanks for your help !

**Comment by prsntmaurya** [comment]
This issue is already addressed in #25. Please refer to it.
