### ISSUE TITLE
python3 opencv 3.4.1 

### ISSUE THREAD

**Issue by hiteshn97** [ITCoders/Human-detection-and-Tracking#31]
# Issues should contain the following details which increases the probability of it get resolved quickly

* **Exact error or Issue details**
* **OpenCV Version**
* **Python Version**
* **Operating System**
* **Changes done, if any in the original code**

**Comment by arpit1997** [comment]
@hiteshn97  there is no information in this issue. What is your issue? I see that you have opened another issue https://github.com/ITCoders/Human-detection-and-Tracking/issues/32 If this was a mistake please confirm so we can close this issue. cc: @prsntmaurya

**Comment by hiteshn97** [comment]
Sorry, it's a mistake.
