### ISSUE TITLE
core dump occurred when running ./humandetect ../GEM_time.mp4 

### ISSUE THREAD

**Issue by snowuyl** [ITCoders/Human-detection-and-Tracking#34]
Hi Sir,
       core dump occurred when  I type the following command 
./humandetect ../GEM_time.mp4 
opencv_contrib-3.4.1/modules/face/src/facerec.cpp, line 61
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1) /opencv_contrib-3.4.1/modules/face/src/facerec.cpp:61: error: (-2) File can't be opened for reading! in function read

Aborted (core dumped)

Could you kindly to give a hint about how to solve this issue?

snowuyl

**Comment by prsntmaurya** [comment]
Have you tried with other mp4 files.
