### ISSUE TITLE
Labelling Issue

### ISSUE THREAD

**Issue by mailrdhegde** [ITCoders/Human-detection-and-Tracking#36]
# Issues should contain the following details which increases the probability of it get resolved quickly

when the any of the face is detected from camera it shows label dynamically changing. like 4,7,22,34,53
so i m not able to understand what are these labels..

looking forward to this.
thanks..

**Comment by prsntmaurya** [comment]
The labels shown are the predicted classes ie: the number corresponding to respective person after recognition

If the labels showing are random then, your training is not correct.

**Comment by Grv02** [comment]
When i m running the program as per instructions
1. training the model image using create_model.py -i data/
2.after that i m running main.py -v video/
and the video provided is from code folder itself
but in the output the label is 1 , 2, and 3 for the same time.
i m not understanding why this is happening.
Please find the screenshot.
![screenshot from 2018-08-30 10-59-21](https://user-images.githubusercontent.com/37537513/44831506-7b3aba00-ac44-11e8-8cd0-5e01a6e49682.png)
![screenshot from 2018-08-30 10-59-25](https://user-images.githubusercontent.com/37537513/44831507-7b3aba00-ac44-11e8-8d96-df398ded1f21.png)
![screenshot from 2018-08-30 10-59-26](https://user-images.githubusercontent.com/37537513/44831508-7bd35080-ac44-11e8-8fe5-c12ba63ec823.png)

please look into this.
thankyou
ding Screenshot from 2018-08-30 10-59-25.png…]()

**Comment by prsntmaurya** [comment]
Hi,
This problem is because you are training for 3 people but the video has another person in it.
Therefore the prediction is random But you can see one thing clearly the confidence value is more in all the 3 cases.

Note: Higher confidence value implies that the unknown person is present but his or her face is most similar to the person whose label is shown.
