### ISSUE TITLE
error in runing code

### ISSUE THREAD

**Issue by mhmd-shadfar** [ITCoders/Human-detection-and-Tracking#37]
* **Exact error or Issue details**
when i run the code with this command python3 main.py in terminal i got this following error : 
usage: main.py [-h] -v VIDEOS
main.py: error: the following arguments are required: -v/--videos
OpenCV Version = 3.2.0
Python Version = 3.6.5
Operating System = ubuntu 18.04

**Comment by prsntmaurya** [comment]
Please specify the path of video.
eg: python3 main.py /video

**Comment by mhmd-shadfar** [comment]
thanks for response.
i do this steps to run the code:
1) cd to Human-detection-and-Tracking-master 
2)python3 main.py /video
i get that error again.

usage: main.py [-h] -v VIDEOS
main.py: error: the following arguments are required: -v/--videos
