### ISSUE TITLE
neural network

### ISSUE THREAD

**Issue by hodaghezavati** [ITCoders/Human-detection-and-Tracking#41]
hi, i want to ask what kind of neural network you used in order to detect human or face in your project and how did you train it?

**Comment by prsntmaurya** [comment]
Hello, we haven't used any neural networks. For the purpose of face detection, HAAR features are used and HOG features are used for Person detection. Please refer to the shared project report for more information.

**Comment by hodaghezavati** [comment]
hi, thank you for answering me
i have found your project quite great
may i ask one more question please?
for labeling detected faces can i give a name?
for example i give my name to my picture in dataset and then do the
training. is it possible? where can i make the changes?

**Comment by prsntmaurya** [comment]
You can use custom names for images but for that, you have to make certain changes in the code _create_face_model.py_.
The current _create_face_model.py_ accepts the images in the following format:
subject01.1.jpg
subject01.2.jpg
...
subject01.100.jpg

subject02.1.jpg
...
subject02.100.jpg

Here the number just after the word "subject" is class ie: it indicates the person to which image belongs to.
Example: 
subject01, subject02 are two different persons.
subject01.1.jpg, subject01.2.jpg are images of same persons ie: subject01
subject01.1.jpg, subject02.1.jpg are images of different persons ie: subject01

**Comment by hodaghezavati** [comment]
Thank you very much for your explanation.
